/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames_paciente;

import java.awt.Font;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.connector.myConnection;
import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;

/**
 *
 * @author PabloCarrijo
 */
public class AddFun extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fun
     */
    private Connection conn = null;
    private PreparedStatement st = null;
    private ResultSet rs = null;
    private Integer flagName = 0;
    private Integer flagCPF = 0;
    private Integer flagRG = 0;
    private Integer flagNacionalidade = 0;
    private Integer flagCEP = 0;
    private Integer flagCidade = 0;
    private Integer flagBairro = 0;
    private Integer flagRua = 0;
    private Integer flagNumero = 0;
    private Integer flagEmail = 0;
    private Integer flagTelefone = 0;
    private Integer flagBancoNome = 0;
    private Integer flagAgencia = 0;
    private Integer flagCPFTitular = 0;
    private Integer flagNomeTitular = 0;
    private Integer flagSalario = 0;
    private Integer flagDataNascimento = 0;

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public AddFun() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);


        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Solteiro(a)",
            "Casado(a)",
            "Viúvo(a)",
            "Divorciado(a)",
            "União estável"
        }));

        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Gerente geral",
            "Subgerente",
            "Supervisor da loja",
            "Auxiliar administrativo",
            "Financeio/Contador",
            "Analista de compras"
        }));

        cadastrarButtonFuncionario.setFont(new Font("Arial", Font.BOLD, 15));

        textFieldCEPFun.setText("00000000");
        textFieldTelefoneFun.setText("(00) 0 0000-0000");
        textFieldDataNascimento.setText("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textFieldNomeFunc = new javax.swing.JTextField();
        textFieldNomeCpf = new javax.swing.JTextField();
        textFieldCEPFun = new javax.swing.JTextField();
        textFieldBairroFun = new javax.swing.JTextField();
        textFieldNumeroFun = new javax.swing.JTextField();
        textFieldDataNascimento = new javax.swing.JTextField();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        textFieldTelefoneFun = new javax.swing.JTextField();
        textFieldEmailFun = new javax.swing.JTextField();
        comboBoxCargo = new javax.swing.JComboBox<>();
        textFieldNomeBancoFun = new javax.swing.JTextField();
        textFieldAgenciaFun = new javax.swing.JTextField();
        textFieldSalarioFun = new javax.swing.JTextField();
        textFieldComplementoFun = new javax.swing.JTextField();
        textFieldRuaFun = new javax.swing.JTextField();
        textFieldCidadeFun = new javax.swing.JTextField();
        cadastrarButtonFuncionario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textFiledNumeroContaFun = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1000, 577));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Paciente"));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1099, 541));

        textFieldNomeFunc.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNomeFunc.setForeground(new java.awt.Color(51, 51, 51));
        textFieldNomeFunc.setForeground(new java.awt.Color(51, 51, 51));
        textFieldNomeFunc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldNomeFunc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNomeFuncFocusGained(evt);
            }
        });
        textFieldNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeFuncActionPerformed(evt);
            }
        });

        textFieldNomeCpf.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNomeCpf.setForeground(new java.awt.Color(51, 51, 51));
        textFieldNomeCpf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldNomeCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNomeCpfFocusGained(evt);
            }
        });
        textFieldNomeCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeCpfActionPerformed(evt);
            }
        });

        textFieldCEPFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCEPFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldCEPFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CEP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldCEPFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldCEPFunFocusGained(evt);
            }
        });
        textFieldCEPFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCEPFunActionPerformed(evt);
            }
        });

        textFieldBairroFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldBairroFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldBairroFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bairro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldBairroFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldBairroFunFocusGained(evt);
            }
        });

        textFieldNumeroFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNumeroFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldNumeroFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldNumeroFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNumeroFunFocusGained(evt);
            }
        });

        textFieldDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        textFieldDataNascimento.setForeground(new java.awt.Color(51, 51, 51));
        textFieldDataNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data de nascimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldDataNascimento.setCaretColor(new java.awt.Color(255, 255, 255));
        textFieldDataNascimento.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textFieldDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldDataNascimentoFocusGained(evt);
            }
        });
        textFieldDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDataNascimentoActionPerformed(evt);
            }
        });

        comboBoxEstadoCivil.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxEstadoCivil.setForeground(new java.awt.Color(51, 51, 51));
        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstadoCivilActionPerformed(evt);
            }
        });

        textFieldTelefoneFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldTelefoneFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldTelefoneFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldTelefoneFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldTelefoneFunFocusGained(evt);
            }
        });

        textFieldEmailFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldEmailFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldEmailFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldEmailFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEmailFunFocusGained(evt);
            }
        });

        comboBoxCargo.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxCargo.setForeground(new java.awt.Color(51, 51, 51));
        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCargoActionPerformed(evt);
            }
        });

        textFieldNomeBancoFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNomeBancoFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldNomeBancoFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do banco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldNomeBancoFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNomeBancoFunFocusGained(evt);
            }
        });

        textFieldAgenciaFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldAgenciaFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldAgenciaFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agência", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldAgenciaFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldAgenciaFunFocusGained(evt);
            }
        });

        textFieldSalarioFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldSalarioFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldSalarioFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldSalarioFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldSalarioFunFocusGained(evt);
            }
        });

        textFieldComplementoFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldComplementoFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldComplementoFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Complemento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        textFieldRuaFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldRuaFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldRuaFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldRuaFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldRuaFunFocusGained(evt);
            }
        });

        textFieldCidadeFun.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCidadeFun.setForeground(new java.awt.Color(51, 51, 51));
        textFieldCidadeFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        textFieldCidadeFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldCidadeFunFocusGained(evt);
            }
        });

        cadastrarButtonFuncionario.setBackground(new java.awt.Color(0, 0, 0));
        cadastrarButtonFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarButtonFuncionario.setText("Cadastrar Paciente");
        cadastrarButtonFuncionario.setBorder(null);
        cadastrarButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonFuncionarioActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textFiledNumeroContaFun.setBackground(new java.awt.Color(255, 255, 255));
        textFiledNumeroContaFun.setForeground(new java.awt.Color(51, 51, 51));
        textFiledNumeroContaFun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número da conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Dados pessoais");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Cargo empresarial");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Estado civil");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Contato");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Endereço");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Dados bancários");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(textFieldRuaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldComplementoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldCEPFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldNomeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNomeBancoFun)
                    .addComponent(textFieldAgenciaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFiledNumeroContaFun)
                    .addComponent(textFieldSalarioFun, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(textFieldEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastrarButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNomeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCEPFun))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldComplementoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRuaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNomeBancoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFiledNumeroContaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSalarioFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAgenciaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        textFieldNomeFunc.getAccessibleContext().setAccessibleName("");

        jPanel3.add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("Cadastro Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buscaCEP();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textFieldCidadeFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCidadeFunFocusGained
        if (flagCidade == 0) {
            textFieldCidadeFun.setText("");
        }
    }//GEN-LAST:event_textFieldCidadeFunFocusGained

    private void textFieldRuaFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldRuaFunFocusGained
        if (flagRua == 0) {
            textFieldRuaFun.setText("");
        }
    }//GEN-LAST:event_textFieldRuaFunFocusGained

    private void textFieldSalarioFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldSalarioFunFocusGained
        if (flagSalario == 0) {
            textFieldSalarioFun.setText("");
        }
    }//GEN-LAST:event_textFieldSalarioFunFocusGained

    private void textFieldAgenciaFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldAgenciaFunFocusGained
        if (flagAgencia == 0) {
            textFieldAgenciaFun.setText("");
        }
    }//GEN-LAST:event_textFieldAgenciaFunFocusGained

    private void textFieldNomeBancoFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNomeBancoFunFocusGained
        if (flagBancoNome == 0) {
            textFieldNomeBancoFun.setText("");
        }
    }//GEN-LAST:event_textFieldNomeBancoFunFocusGained

    private void comboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCargoActionPerformed

    private void textFieldEmailFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailFunFocusGained
        if (flagEmail == 0) {
            textFieldEmailFun.setText("");
        }
    }//GEN-LAST:event_textFieldEmailFunFocusGained

    private void textFieldTelefoneFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldTelefoneFunFocusGained
        if (flagTelefone == 0) {
            textFieldTelefoneFun.setText("");
        }
    }//GEN-LAST:event_textFieldTelefoneFunFocusGained

    private void comboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstadoCivilActionPerformed

    }//GEN-LAST:event_comboBoxEstadoCivilActionPerformed

    private void textFieldDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDataNascimentoActionPerformed

    private void textFieldDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDataNascimentoFocusGained
        if (flagDataNascimento == 0) {
            textFieldDataNascimento.setText("");
        }
    }//GEN-LAST:event_textFieldDataNascimentoFocusGained

    private void textFieldNumeroFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNumeroFunFocusGained
        if (flagNumero == 0) {
            textFieldNumeroFun.setText("");
        }
    }//GEN-LAST:event_textFieldNumeroFunFocusGained

    private void textFieldBairroFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldBairroFunFocusGained
        if (flagBairro == 0) {
            textFieldBairroFun.setText("");
        }
    }//GEN-LAST:event_textFieldBairroFunFocusGained

    private void textFieldCEPFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCEPFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCEPFunActionPerformed

    private void textFieldCEPFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCEPFunFocusGained
        if (flagCEP == 0) {
            textFieldCEPFun.setText("");
        }
    }//GEN-LAST:event_textFieldCEPFunFocusGained

    private void textFieldNomeCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeCpfActionPerformed

    private void textFieldNomeCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNomeCpfFocusGained
        if (flagCPF == 0) {
            textFieldNomeCpf.setText("");
        }
    }//GEN-LAST:event_textFieldNomeCpfFocusGained

    //SUBTEXTO NAS TEXTFIELDS
    private void textFieldNomeFuncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNomeFuncFocusGained
        if (flagName == 0) {
            textFieldNomeFunc.setText("");
        }
    }//GEN-LAST:event_textFieldNomeFuncFocusGained

    private void textFieldNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeFuncActionPerformed

    private void cadastrarButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonFuncionarioActionPerformed

        //TABLE FUNCIONARIO
        String funcionarioName = textFieldNomeFunc.getText();
        String funcionarioCPF = textFieldNomeCpf.getText();
        String funcionarioEstadoCivil = (String) comboBoxEstadoCivil.getSelectedItem();
        String funcionarioCargo = (String) comboBoxCargo.getSelectedItem();

        String funcionarioDataNascimento = textFieldDataNascimento.getText();
        LocalDate dataAniversario = LocalDate.parse(funcionarioDataNascimento, dtf);

        //==============================
        //TABLE ENDERECO
        String funcionarioCEPEndereco = textFieldCEPFun.getText();
        String funcionarioCidadeEndereco = textFieldCidadeFun.getText();
        String funcionarioRuaEndereco = textFieldRuaFun.getText();
        String funcionarioComplementoEndereco = textFieldComplementoFun.getText();
        String funcionarioBairroEndereco = textFieldBairroFun.getText();

        String funcionarioNumeroEndereco = textFieldNumeroFun.getText();
        Integer funcionarioNumeroEnderecoInt = Integer.parseInt(funcionarioNumeroEndereco);

        //=============================
        //TABLE CONTATO
        String funcionarioTelefoneContato = textFieldTelefoneFun.getText();
        String funcionarioEmailContato = textFieldEmailFun.getText();

        //==============================
        //TABLE DADOS BANCARIOS
        String funcionarioNomeBanco = textFieldNomeBancoFun.getText();

        String funcionarioNumeroConta = textFiledNumeroContaFun.getText();
        Integer funcionarioNumeroContaInt = Integer.parseInt(funcionarioNumeroConta);

        String funcionarioAgenciaBanco = textFieldAgenciaFun.getText();
        Integer funcionarioAgenciaBancoInt = Integer.parseInt(funcionarioAgenciaBanco);

        String funcionarioSalarioBanco = textFieldSalarioFun.getText();
        Double funcionarioSalarioBancoDouble = Double.parseDouble(funcionarioSalarioBanco);

        //==============================
        try {
            conn = myConnection.getConexao();
            if (conn == null || conn.isClosed()) {
                System.out.println("Impossível realizar conexão com banco de dados...");
            } else {
                System.out.println("Conexão com o banco estabelecida!!!");
            }

            //=======================
            //Inserindo endereco do funcionario
            String sql = "INSERT INTO endereco "
            + "(cep, cidade, bairro, rua, numero, complemento)"
            + " VALUES"
            + " (?, ?, ?, ?, ?, ?)";

            st = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            st.setString(1, funcionarioCEPEndereco);
            st.setString(2, funcionarioCidadeEndereco);
            st.setString(3, funcionarioBairroEndereco);
            st.setString(4, funcionarioRuaEndereco);
            st.setInt(5, funcionarioNumeroEnderecoInt);
            st.setString(6, funcionarioComplementoEndereco);

            st.executeUpdate();

            ResultSet rs = st.getGeneratedKeys();
            int idEndereco = 0;
            if (rs.next()) {
                idEndereco = rs.getInt(1);
            }
            rs.close();
            st.close();

            //============================
            //Inserindo dados bancarios do funcionario
            sql = "INSERT INTO dados_bancarios"
            + " (numero_conta, nome_banco, agencia, salario)"
            + " VALUES"
            + " (?, ?, ?, ?)";
            st = conn.prepareStatement(sql);
            st.setInt(1, funcionarioNumeroContaInt);
            st.setString(2, funcionarioNomeBanco);
            st.setInt(3, funcionarioAgenciaBancoInt);
            st.setDouble(4, funcionarioSalarioBancoDouble);

            st.executeUpdate();
            st.close();
            //============================

            //Inserindo dados do funcionario
            sql = "INSERT INTO paciente"
            + " (id_endereco, numero_conta_bancaria, nome, cpf, data_nascimento,"
            + "cargo, estado_civil)"
            + " VALUES"
            + " (?, ?, ?, ?, ?, ?, ?)";
            st = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            st.setInt(1, idEndereco);
            st.setInt(2, funcionarioNumeroContaInt);
            st.setString(3, funcionarioName);
            st.setString(4, funcionarioCPF);
            st.setDate(5, java.sql.Date.valueOf(dataAniversario));
            st.setString(6, funcionarioCargo);
            st.setString(7, funcionarioEstadoCivil);

            st.executeUpdate();

            rs = st.getGeneratedKeys();
            int idFuncionario = 0;
            if (rs.next()) {
                idFuncionario = rs.getInt(1);
            }
            rs.close();
            st.close();

            //============================
            //ADICIONANDO CONTATO DO FUNCIONARIO
            sql = "INSERT INTO contato"
            + " (id_paciente, email, telefone)"
            + " VALUES"
            + " (?, ?, ?)";

            st = conn.prepareStatement(sql);
            st.setInt(1, idFuncionario);
            st.setString(2, funcionarioEmailContato);
            st.setString(3, funcionarioTelefoneContato);
            st.executeUpdate();
            st.close();

            JOptionPane.showInternalMessageDialog(getDesktopPane(), "Paciente cadastrado com sucesso");

        } catch (SQLException e) {
            JOptionPane.showInternalMessageDialog(this, "Erro ao conectar..." + e.getMessage());
        } finally {
            try {
                if (conn != null && (!conn.isClosed())) {
                    myConnection.closeConnection(conn, st);
                    textFieldNomeFunc.setText("");
                    textFieldNomeCpf.setText("");
                    textFieldCEPFun.setText("");
                    textFieldCidadeFun.setText("");
                    textFieldTelefoneFun.setText("");
                    textFieldEmailFun.setText("");
                    textFieldBairroFun.setText("");
                    textFieldRuaFun.setText("");
                    textFieldComplementoFun.setText("");
                    textFieldNomeBancoFun.setText("");
                    textFieldAgenciaFun.setText("");
                    textFieldNumeroFun.setText("");
                    textFieldSalarioFun.setText("");
                    textFieldDataNascimento.setText("");
                    textFiledNumeroContaFun.setText("");
                    comboBoxEstadoCivil.setSelectedItem("Solteiro(a)");
                    comboBoxCargo.setSelectedItem("Gerente geral");
                    
                }
            } catch (SQLException ex) {
                JOptionPane.showInternalMessageDialog(getDesktopPane(), "Erro ao fechar banco de dados " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_cadastrarButtonFuncionarioActionPerformed

    private void buscaCEP() {
        String logradouro = "";
        String tipoLogradouro = "";
        String resultado = null;

        String cep = textFieldCEPFun.getText();
        try {
            URL url = new URL("http://cep.republicavirtual.com.br/web_cep.php?cep=" + cep + "&formato=xml");
            SAXReader xml = new SAXReader();
            Document documento = xml.read(url);
            Element root = documento.getRootElement();

            for (Iterator<Element> it = root.elementIterator(); it.hasNext();) {
                Element ele = it.next();
                if (ele.getQualifiedName().equals("cidade")) {
                    textFieldCidadeFun.setText(ele.getText());
                } else if (ele.getQualifiedName().equals("bairro")) {
                    textFieldBairroFun.setText(ele.getText());
                } else if (ele.getQualifiedName().equals("logradouro")) {
                    textFieldRuaFun.setText(ele.getText());
                }
            }

        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(getDesktopPane(),"Erro ao acessar CEP");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButtonFuncionario;
    private javax.swing.JComboBox<String> comboBoxCargo;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textFieldAgenciaFun;
    private javax.swing.JTextField textFieldBairroFun;
    private javax.swing.JTextField textFieldCEPFun;
    private javax.swing.JTextField textFieldCidadeFun;
    private javax.swing.JTextField textFieldComplementoFun;
    private javax.swing.JTextField textFieldDataNascimento;
    private javax.swing.JTextField textFieldEmailFun;
    private javax.swing.JTextField textFieldNomeBancoFun;
    private javax.swing.JTextField textFieldNomeCpf;
    private javax.swing.JTextField textFieldNomeFunc;
    private javax.swing.JTextField textFieldNumeroFun;
    private javax.swing.JTextField textFieldRuaFun;
    private javax.swing.JTextField textFieldSalarioFun;
    private javax.swing.JTextField textFieldTelefoneFun;
    private javax.swing.JTextField textFiledNumeroContaFun;
    // End of variables declaration//GEN-END:variables
}
