/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import java.awt.Font;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class AddFun extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fun
     */
    private Connection conn = null;
    private PreparedStatement st = null;
    private ResultSet rs = null;
    
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    private Connection getConnection()throws SQLException{
        
        if(conn == null || conn.isClosed()){
            conn = myConnection.getConexao();
            if(conn == null){
                System.out.println("Erro ao conectar com banco de dados");
            }
            else{
                System.out.println("Conexao de dados feita com sucesso");
            }
        }
        return conn;
    }
    
    private void closeConnection(){
        if(conn != null){
            try {
                conn.close();
            } catch (SQLException ex) {
                System.getLogger(AddFun.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }
    
    public AddFun() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Solteiro(a)",
            "Casado(a)",
            "Viúvo(a)",
            "Divorciado(a)",
            "União estável"
        }));
        
        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Gerente geral",
            "Subgerente",
            "Supervisor da loja",
            "Auxiliar administrativo",
            "Financeio/Contador",
            "Analista de compras"
        }));
        
        comboBoxTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Conta corrente",
            "Conta poupança",
            "Conta salário"
        }));
        
       cadastroDadosLabel.setFont(new Font("Arial", Font.BOLD, 15));
       cadastroEnderecoLabel.setFont(new Font("Arial", Font.BOLD, 15));
       cadastroContatoLabel.setFont(new Font("Arial", Font.BOLD, 15));
       cadastroDadosBancariosLabel.setFont(new Font("Arial", Font.BOLD, 15));
       cadastroDataNascimentoLabel.setFont(new Font("Arial", Font.BOLD, 15));
       cadastroCargoEmpresarialLabel.setFont(new Font("Arial", Font.BOLD, 15));
       cadastrarButtonFuncionario.setFont(new Font("Arial", Font.BOLD, 30));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNomeFunc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldNomeCpf = new javax.swing.JTextField();
        cadastroEnderecoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldCEPFun = new javax.swing.JTextField();
        cadastroDadosLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldBairroFun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldNumeroFun = new javax.swing.JTextField();
        cadastroDataNascimentoLabel = new javax.swing.JLabel();
        textFieldDataNascimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFieldRgFun = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textFieldNacionalidadeFun = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        cadastroContatoLabel = new javax.swing.JLabel();
        EnderecoLabel1 = new javax.swing.JLabel();
        textFieldTelefoneFun = new javax.swing.JTextField();
        EnderecoLabel2 = new javax.swing.JLabel();
        textFieldEmailFun = new javax.swing.JTextField();
        cadastroCargoEmpresarialLabel = new javax.swing.JLabel();
        comboBoxCargo = new javax.swing.JComboBox<>();
        cadastroDadosBancariosLabel = new javax.swing.JLabel();
        textFieldNomeTitularFun = new javax.swing.JTextField();
        EnderecoLabel3 = new javax.swing.JLabel();
        EnderecoLabel4 = new javax.swing.JLabel();
        textFieldNomeBancoFun = new javax.swing.JTextField();
        EnderecoLabel5 = new javax.swing.JLabel();
        comboBoxTipoConta = new javax.swing.JComboBox<>();
        EnderecoLabel6 = new javax.swing.JLabel();
        textFieldAgenciaFun = new javax.swing.JTextField();
        textFieldCPFTitularFun = new javax.swing.JTextField();
        EnderecoLabel7 = new javax.swing.JLabel();
        EnderecoLabel8 = new javax.swing.JLabel();
        textFieldSalarioFun = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textFieldComplementoFun = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textFieldRuaFun = new javax.swing.JTextField();
        textFieldCidadeFun = new javax.swing.JTextField();
        cadastrarButtonFuncionario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 577));

        jPanel1.setBackground(new java.awt.Color(80, 80, 80));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1099, 541));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do  funcionario");

        textFieldNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeFuncActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF");

        textFieldNomeCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeCpfActionPerformed(evt);
            }
        });

        cadastroEnderecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroEnderecoLabel.setText("Endereço");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CEP");

        textFieldCEPFun.setText("-");

        cadastroDadosLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroDadosLabel.setText("Dados");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bairro");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rua");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Número");

        cadastroDataNascimentoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroDataNascimentoLabel.setText("Data de nascimento");
        cadastroDataNascimentoLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cadastroDataNascimentoLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        textFieldDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDataNascimentoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RG");

        textFieldRgFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRgFunActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nacionalidade");

        textFieldNacionalidadeFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNacionalidadeFunActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estado civil");

        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstadoCivilActionPerformed(evt);
            }
        });

        cadastroContatoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroContatoLabel.setText("Contato");

        EnderecoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel1.setText("Telefone");

        EnderecoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel2.setText("Email");

        cadastroCargoEmpresarialLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroCargoEmpresarialLabel.setText("Cargo empresarial");
        cadastroCargoEmpresarialLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cadastroCargoEmpresarialLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCargoActionPerformed(evt);
            }
        });

        cadastroDadosBancariosLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroDadosBancariosLabel.setText("Dados bancários");

        textFieldNomeTitularFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeTitularFunActionPerformed(evt);
            }
        });

        EnderecoLabel3.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel3.setText("Tipo de conta");

        EnderecoLabel4.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel4.setText("Agência");

        EnderecoLabel5.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel5.setText("Nome do banco");

        comboBoxTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoContaActionPerformed(evt);
            }
        });

        EnderecoLabel6.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel6.setText("Nome do titular");

        EnderecoLabel7.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel7.setText("CPF do titular");

        EnderecoLabel8.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel8.setText("Salario");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Complemento");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cidade");

        cadastrarButtonFuncionario.setForeground(new java.awt.Color(255, 0, 0));
        cadastrarButtonFuncionario.setText("Cadastrar");
        cadastrarButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonFuncionarioActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/arrow_left.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastroDadosLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(textFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(textFieldNacionalidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldNomeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7)
                                            .addComponent(textFieldRgFun, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(textFieldCEPFun, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(246, 246, 246)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(textFieldBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastroDataNascimentoLabel)
                                    .addComponent(jLabel12)
                                    .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(textFieldRuaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(textFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(textFieldNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cadastroCargoEmpresarialLabel)))))
                            .addComponent(cadastroEnderecoLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastroContatoLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EnderecoLabel1)
                                            .addComponent(textFieldTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EnderecoLabel2)
                                            .addComponent(textFieldEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(textFieldCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastroDadosBancariosLabel)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textFieldComplementoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(EnderecoLabel5)
                                                .addComponent(textFieldNomeBancoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EnderecoLabel4)
                                                .addComponent(textFieldAgenciaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textFieldCPFTitularFun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EnderecoLabel7))
                                            .addGap(51, 51, 51)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textFieldNomeTitularFun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EnderecoLabel3)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(EnderecoLabel6)
                                                        .addComponent(textFieldSalarioFun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EnderecoLabel8)
                                                        .addComponent(comboBoxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(57, 57, 57)
                                                    .addComponent(cadastrarButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addComponent(jButton1))
                .addGap(1002, 1002, 1002))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cadastroDadosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastroDataNascimentoLabel)
                        .addComponent(cadastroCargoEmpresarialLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNomeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldRgFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNacionalidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(cadastroEnderecoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldCEPFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldRuaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldComplementoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroContatoLabel)
                    .addComponent(cadastroDadosBancariosLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecoLabel1)
                    .addComponent(EnderecoLabel2)
                    .addComponent(EnderecoLabel3)
                    .addComponent(EnderecoLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNomeBancoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnderecoLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EnderecoLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNomeTitularFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAgenciaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EnderecoLabel7)
                            .addComponent(EnderecoLabel8))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldCPFTitularFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSalarioFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cadastrarButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeFuncActionPerformed

    private void textFieldNomeCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeCpfActionPerformed

    private void cadastroDataNascimentoLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cadastroDataNascimentoLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroDataNascimentoLabelAncestorAdded

    private void textFieldRgFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRgFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRgFunActionPerformed

    private void textFieldNacionalidadeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNacionalidadeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNacionalidadeFunActionPerformed

    private void comboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstadoCivilActionPerformed

    }//GEN-LAST:event_comboBoxEstadoCivilActionPerformed

    private void cadastroCargoEmpresarialLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cadastroCargoEmpresarialLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroCargoEmpresarialLabelAncestorAdded

    private void comboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCargoActionPerformed

    private void comboBoxTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTipoContaActionPerformed

    private void textFieldNomeTitularFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeTitularFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeTitularFunActionPerformed

    private void cadastrarButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonFuncionarioActionPerformed
        
        String funcionarioName = textFieldNomeFunc.getText();
        String funcionarioCPF = textFieldNomeCpf.getText();
        String funcionarioNacionalidade = textFieldNacionalidadeFun.getText();
        String funcionarioRG = textFieldRgFun.getText();
        String funcionarioCEPEndereco = textFieldCEPFun.getText();
        String funcionarioCidadeEndereco = textFieldCidadeFun.getText();
        String funcionarioTelefoneContato = textFieldTelefoneFun.getText();
        String funcionarioEmailContato = textFieldEmailFun.getText();
        String funcionarioBairroContato = textFieldBairroFun.getText();
        String funcionarioRuaEndereco = textFieldRuaFun.getText();
        String funcionarioComplementoEndereco = textFieldComplementoFun.getText();
        String funcionarioNomeBanco = textFieldNomeBancoFun.getText();
        String funcionarioNomeTitularBanco = textFieldNomeTitularFun.getText();
        String funcionarioCPFBanco = textFieldCPFTitularFun.getText();
        String funcionarioEstadoCivil = (String) comboBoxEstadoCivil.getSelectedItem();
        String funcionarioCargo = (String) comboBoxCargo.getSelectedItem();
        String funcionarioTipoContaBanco = (String) comboBoxTipoConta.getSelectedItem();
        

        String funcionarioDataNascimento = textFieldDataNascimento.getText();
        LocalDate dataAniversario = LocalDate.parse(funcionarioDataNascimento, dtf);
        
        String funcionarioNumeroEndereco = textFieldNumeroFun.getText();
        String funcionarioAgenciaBanco = textFieldAgenciaFun.getText();
        String funcionarioSalarioBanco = textFieldSalarioFun.getText();
        
        Integer funcionarioNumeroEnderecoInt = Integer.parseInt(funcionarioNumeroEndereco);
        Integer funcionarioAgenciaBancoInt = Integer.parseInt(funcionarioAgenciaBanco);
        Double funcionarioSalarioBancoDouble = Double.parseDouble(funcionarioSalarioBanco);
        
        
        try{
            conn = myConnection.getConexao();
            if(conn == null || conn.isClosed()){
                System.out.println("Impossível realizar conexão com banco de dados...");
            }
            else System.out.println("Conexão com o banco estabelecida!!!");
                
            String sql = "INSERT INTO funcionarios "
                    + "(nome, cpf, rg,"
                    + " nacionalidade, data_nascimento, estado_civil,"
                    + " cargo, cep, cidade, bairro, rua, numero, complemento,"
                    + " telefone, email,"
                    + " nome_banco, salario, agencia, tipo_conta, nome_titular, cpf_titular)"
                    + " VALUES"
                    + " (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            st = conn.prepareStatement(sql);
            st.setString(1, funcionarioName);
            st.setString(2, funcionarioCPF);
            st.setString(3, funcionarioRG);
            st.setString(4, funcionarioNacionalidade);
            st.setDate(5, Date.valueOf(dataAniversario));
            st.setString(6, funcionarioEstadoCivil);
            st.setString(7, funcionarioCargo);
            st.setString(8, funcionarioCEPEndereco);
            st.setString(9, funcionarioCidadeEndereco);
            st.setString(10, funcionarioBairroContato);
            st.setString(11, funcionarioRuaEndereco);
            st.setInt(12, funcionarioNumeroEnderecoInt);
            st.setString(13, funcionarioComplementoEndereco);
            st.setString(14, funcionarioTelefoneContato);
            st.setString(15, funcionarioEmailContato);
            st.setString(16, funcionarioNomeBanco);
            st.setDouble(17, funcionarioSalarioBancoDouble);
            st.setInt(18, funcionarioAgenciaBancoInt);
            st.setString(19, funcionarioTipoContaBanco);
            st.setString(20, funcionarioNomeTitularBanco);
            st.setString(21, funcionarioCPFBanco);
            
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso");            
        }
        
        catch(SQLException e){
            System.out.println("Erro ao conectar..." + e.getMessage());
        }
        finally{
            try {
                if(conn != null && (!conn.isClosed())){
                    myConnection.closeConnection(conn, st);
                    textFieldNomeFunc.setText("");
                    textFieldNomeCpf.setText("");
                    textFieldNacionalidadeFun.setText("");
                    textFieldRgFun.setText("");
                    textFieldCEPFun.setText("");
                    textFieldCidadeFun.setText("");
                    textFieldTelefoneFun.setText("");
                    textFieldEmailFun.setText("");
                    textFieldBairroFun.setText("");
                    textFieldRuaFun.setText("");
                    textFieldComplementoFun.setText("");
                    textFieldNomeBancoFun.setText("");
                    textFieldAgenciaFun.setText("");
                    textFieldNumeroFun.setText("");
                    textFieldNomeTitularFun.setText("");
                    textFieldSalarioFun.setText("");
                    textFieldNomeTitularFun.setText("");
                    textFieldSalarioFun.setText("");
                    textFieldCPFTitularFun.setText("");
                    textFieldDataNascimento.setText("");
                    comboBoxEstadoCivil.setSelectedItem("Solteiro(a)");
                    comboBoxCargo.setSelectedItem("Gerente geral");
                    comboBoxTipoConta.setSelectedItem("Conta corrente");
                    
                }
            } catch (SQLException ex) {
                System.out.println("Erro ao fechar banco de dados " + ex.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_cadastrarButtonFuncionarioActionPerformed

    private void textFieldDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDataNascimentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnderecoLabel1;
    private javax.swing.JLabel EnderecoLabel2;
    private javax.swing.JLabel EnderecoLabel3;
    private javax.swing.JLabel EnderecoLabel4;
    private javax.swing.JLabel EnderecoLabel5;
    private javax.swing.JLabel EnderecoLabel6;
    private javax.swing.JLabel EnderecoLabel7;
    private javax.swing.JLabel EnderecoLabel8;
    private javax.swing.JButton cadastrarButtonFuncionario;
    private javax.swing.JLabel cadastroCargoEmpresarialLabel;
    private javax.swing.JLabel cadastroContatoLabel;
    private javax.swing.JLabel cadastroDadosBancariosLabel;
    private javax.swing.JLabel cadastroDadosLabel;
    private javax.swing.JLabel cadastroDataNascimentoLabel;
    private javax.swing.JLabel cadastroEnderecoLabel;
    private javax.swing.JComboBox<String> comboBoxCargo;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JComboBox<String> comboBoxTipoConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldAgenciaFun;
    private javax.swing.JTextField textFieldBairroFun;
    private javax.swing.JTextField textFieldCEPFun;
    private javax.swing.JTextField textFieldCPFTitularFun;
    private javax.swing.JTextField textFieldCidadeFun;
    private javax.swing.JTextField textFieldComplementoFun;
    private javax.swing.JTextField textFieldDataNascimento;
    private javax.swing.JTextField textFieldEmailFun;
    private javax.swing.JTextField textFieldNacionalidadeFun;
    private javax.swing.JTextField textFieldNomeBancoFun;
    private javax.swing.JTextField textFieldNomeCpf;
    private javax.swing.JTextField textFieldNomeFunc;
    private javax.swing.JTextField textFieldNomeTitularFun;
    private javax.swing.JTextField textFieldNumeroFun;
    private javax.swing.JTextField textFieldRgFun;
    private javax.swing.JTextField textFieldRuaFun;
    private javax.swing.JTextField textFieldSalarioFun;
    private javax.swing.JTextField textFieldTelefoneFun;
    // End of variables declaration//GEN-END:variables
}
