/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class AlterarFunPaneEndereco extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarFunPaneEndereco
     */
    private Connection conn = null;
    private PreparedStatement ps = null;
    private String nameConsulta;
    private ResultSet rs = null;

    public AlterarFunPaneEndereco(String nameConsulta) {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.nameConsulta = nameConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldAlterarNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldAlterarCidade = new javax.swing.JTextField();
        textFieldAlterarRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldAlterarComplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textFieldAlterarBairro = new javax.swing.JTextField();
        textFieldAlterarCEP = new javax.swing.JTextField();

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CEP :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cidade :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Número :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Rua :");

        textFieldAlterarComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarComplementoActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Complemento :");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bairro :");

        textFieldAlterarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarCEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldAlterarBairro)
                    .addComponent(textFieldAlterarCEP)
                    .addComponent(textFieldAlterarCidade)
                    .addComponent(textFieldAlterarNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(textFieldAlterarRua, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(textFieldAlterarComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldAlterarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldAlterarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldAlterarRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAlterarComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarComplementoActionPerformed

    private void textFieldAlterarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarCEPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (conn == null || conn.isClosed()) {
                conn = myConnection.getConexao();
            } else if (conn != null) {
                myConnection.closeConnection(conn, ps);
                conn = myConnection.getConexao();
                System.out.println("Erro ao estabelecer conexão, mas foi reestabelecida");
            }

            String sqlId = "SELECT id_endereco FROM funcionario WHERE nome = ?";
            ps = conn.prepareStatement(sqlId);
            ps.setString(1, nameConsulta);
            rs = ps.executeQuery();
            int idEndereco = -1;
            if(rs.next()){
                idEndereco = rs.getInt("id_endereco");
            }

            String sql = "UPDATE endereco SET "
                    + "cep = ?, cidade = ?, bairro = ?, rua = ?, numero = ?, complemento = ? "
                    + "WHERE id_endereco = ?";

            ps = conn.prepareStatement(sql);
            ps.setString(1, textFieldAlterarCEP.getText());
            ps.setString(2, textFieldAlterarCidade.getText());
            ps.setString(3, textFieldAlterarBairro.getText());
            ps.setString(4, textFieldAlterarRua.getText());
            ps.setInt(5, Integer.parseInt(textFieldAlterarNumero.getText()));
            ps.setString(6, textFieldAlterarComplemento.getText());
            ps.setInt(7, idEndereco);

            int n = ps.executeUpdate();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Erro na alteração");
            }

        } catch (SQLException e) {
            System.out.println("Erro ao conectar...");
        } finally {
            myConnection.closeConnection(conn, ps);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextField getTextFieldAlterarBairro() {
        return textFieldAlterarBairro;
    }

    public void setTextFieldAlterarBairro(String value) {
        textFieldAlterarBairro.setText(value);
    }

    public JTextField getTextFieldAlterarCEP() {
        return textFieldAlterarCEP;
    }

    public void setTextFieldAlterarCEP(String value) {
        textFieldAlterarCEP.setText(value);
    }

    public JTextField getTextFieldAlterarCidade() {
        return textFieldAlterarCidade;
    }

    public void setTextFieldAlterarCidade(String value) {
        textFieldAlterarCidade.setText(value);
    }

    public JTextField getTextFieldAlterarComplemento() {
        return textFieldAlterarComplemento;
    }

    public void setTextFieldAlterarComplemento(String value) {
        textFieldAlterarComplemento.setText(value);
    }

    public JTextField getTextFieldAlterarNumero() {
        return textFieldAlterarNumero;
    }

    public void setTextFieldAlterarNumero(String value) {
        textFieldAlterarNumero.setText(value);
    }

    public JTextField getTextFieldAlterarRua() {
        return textFieldAlterarRua;
    }

    public void setTextFieldAlterarRua(String value) {
        textFieldAlterarRua.setText(value);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textFieldAlterarBairro;
    private javax.swing.JTextField textFieldAlterarCEP;
    private javax.swing.JTextField textFieldAlterarCidade;
    private javax.swing.JTextField textFieldAlterarComplemento;
    private javax.swing.JTextField textFieldAlterarNumero;
    private javax.swing.JTextField textFieldAlterarRua;
    // End of variables declaration//GEN-END:variables
}
