/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class AlterarFunPaneDadosPessoais extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarFunPaneDadosPessoais
     */
    private LocalDate dataNascimento;
    
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    
    private String nomeBusca;
    
    public AlterarFunPaneDadosPessoais(String nomeBusca) {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.nomeBusca = nomeBusca;
        
        
        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Soleiro(a)",
            "Casado(a)",
            "Viúvo(a)",
            "Divorciado(a)",
            "União estável"
        }));
        
        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Gerente geral",
            "Subgerente",
            "Supervisor da loja",
            "Auxiliar administrativo",
            "Financeiro/Contador",
            "Analista de compras"
        }));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldAlterarNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldAlterarCPF = new javax.swing.JTextField();
        textFieldAlterarDataNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        comboBoxCargo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        textFieldAlterarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarNomeActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CPF :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data de nascimento :");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado civil :");

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCargoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cargo empresarial: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldAlterarNome)
                    .addComponent(textFieldAlterarCPF)
                    .addComponent(textFieldAlterarDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(comboBoxEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldAlterarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldAlterarDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAlterarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            if(conn == null || conn.isClosed()){
                conn = myConnection.getConexao();
            }
            else{
                myConnection.closeConnection(conn, ps);
                conn = myConnection.getConexao();
            }
            
            String sql = "UPDATE funcionario SET "
                    + "nome = ?, cpf = ?, data_nascimento = ?, "
                    + "cargo = ?, estado_civil = ? "
                    + "WHERE nome = ?";
            
            ps = conn.prepareStatement(sql);
            
            ps.setString(1, textFieldAlterarNome.getText());
            ps.setString(2, textFieldAlterarCPF.getText());
            
            dataNascimento = LocalDate.parse(textFieldAlterarDataNascimento.getText(), dtf);
            
            ps.setDate(3, Date.valueOf(dataNascimento));
            ps.setString(4, (String) comboBoxCargo.getSelectedItem());
            ps.setString(5, (String) comboBoxEstadoCivil.getSelectedItem());
            ps.setString(6, nomeBusca);
         
            int n = ps.executeUpdate();
            
            if(n > 0){
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!!!");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao alterar!!");
            }
            
        }
        catch(SQLException e){
            System.out.println("Erro ao carregar banco de dados "  + e.getMessage());
        }
        finally{
            myConnection.closeConnection(conn, ps);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCargoActionPerformed

    public JTextField getTextFieldAlterarCPF() {
        return textFieldAlterarCPF;
    }

    public void setTextFieldAlterarCPF(String value) {
        textFieldAlterarCPF.setText(value);
    }

    public JTextField getTextFieldAlterarDataNascimento() {
        return textFieldAlterarDataNascimento;
    }

    public void setTextFieldAlterarDataNascimento(String value) {
        textFieldAlterarDataNascimento.setText(value);
    }

    public void setComboBoxEstadoCivil(String value) {
        comboBoxEstadoCivil.setSelectedItem(value);
    }

    public JTextField getTextFieldAlterarNome() {
        return textFieldAlterarNome;
    }

    public void setTextFieldAlterarNome(String value) {
        textFieldAlterarNome.setText(value);
    }    
    
    public void setComboBoxCargo(String value){
        comboBoxCargo.setSelectedItem(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxCargo;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textFieldAlterarCPF;
    private javax.swing.JTextField textFieldAlterarDataNascimento;
    private javax.swing.JTextField textFieldAlterarNome;
    // End of variables declaration//GEN-END:variables
}
