/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class AlterarFunPaneDadosBancarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarFunPaneDadosBancarios
     */
    
    private Connection conn = null;
    private PreparedStatement ps = null;
    private String nameConsulta;
    
    public AlterarFunPaneDadosBancarios(String nameConsulta) {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.nameConsulta = nameConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldAlterarNomeTitular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldAlterarNomeBanco = new javax.swing.JTextField();
        textFieldAlterarTipoConta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldAlterarCPFTitular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textFieldAlterarAgencia = new javax.swing.JTextField();
        textFieldAlterarSalario = new javax.swing.JTextField();

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Salario  :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome banco :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome titular :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo conta :");

        textFieldAlterarCPFTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarCPFTitularActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CPF titular :");

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agência :");

        textFieldAlterarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarSalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldAlterarAgencia)
                    .addComponent(textFieldAlterarSalario)
                    .addComponent(textFieldAlterarNomeBanco)
                    .addComponent(textFieldAlterarNomeTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(textFieldAlterarTipoConta, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(textFieldAlterarCPFTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldAlterarNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldAlterarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldAlterarTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarCPFTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAlterarCPFTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarCPFTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarCPFTitularActionPerformed

    private void textFieldAlterarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarSalarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            
            if(conn == null || conn.isClosed()){
                conn = myConnection.getConexao();
            }
            else if(conn != null || !conn.isClosed()){
                conn = myConnection.getConexao();
            }
            
            String SQL = "UPDATE funcionarios SET "
                    + "nome_banco = ?, salario = ?, agencia = ?, tipo_conta = ?, nome_titular = ?, "
                    + "cpf_titular = ? "
                    + "WHERE nome = ?";
            ps = conn.prepareStatement(SQL);
            
            ps.setString(1, textFieldAlterarNomeBanco.getText());
            ps.setString(2, textFieldAlterarSalario.getText());
            ps.setString(3, textFieldAlterarAgencia.getText());
            ps.setString(4, textFieldAlterarTipoConta.getText());
            ps.setString(5, textFieldAlterarNomeTitular.getText());
            ps.setString(6, textFieldAlterarCPFTitular.getText());
            ps.setString(7, nameConsulta);
            
            int n = ps.executeUpdate();
            
            if(n > 0){
                JOptionPane.showMessageDialog(null, "Usuario alterado com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao atualizar usuário");
            }
            
        }
        catch(SQLException e){
            System.out.println("Erro ao conectar banco de dados " + e.getMessage());
        }
        finally{
            myConnection.closeConnection(conn, ps);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextField getTextFieldAlterarAgencia() {
        return textFieldAlterarAgencia;
    }

    public void setTextFieldAlterarAgencia(String value) {
        textFieldAlterarAgencia.setText(value);
    }

    public JTextField getTextFieldAlterarCPFTitular() {
        return textFieldAlterarCPFTitular;
    }

    public void setTextFieldAlterarCPFTitular(String value) {
        textFieldAlterarCPFTitular.setText(value);
    }

    public JTextField getTextFieldAlterarNomeBanco() {
        return textFieldAlterarNomeBanco;
    }

    public void setTextFieldAlterarNomeBanco(String value) {
        textFieldAlterarNomeBanco.setText(value);
    }

    public JTextField getTextFieldAlterarNomeTitular() {
        return textFieldAlterarNomeTitular;
    }

    public void setTextFieldAlterarNomeTitular(String value) {
        textFieldAlterarNomeTitular.setText(value);
    }

    public JTextField getTextFieldAlterarSalario() {
        return textFieldAlterarSalario;
    }

    public void setTextFieldAlterarSalario(String value) {
        textFieldAlterarSalario.setText(value);
    }

    public JTextField getTextFieldAlterarTipoConta() {
        return textFieldAlterarTipoConta;
    }

    public void setTextFieldAlterarTipoConta(String value) {
        textFieldAlterarTipoConta.setText(value);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textFieldAlterarAgencia;
    private javax.swing.JTextField textFieldAlterarCPFTitular;
    private javax.swing.JTextField textFieldAlterarNomeBanco;
    private javax.swing.JTextField textFieldAlterarNomeTitular;
    private javax.swing.JTextField textFieldAlterarSalario;
    private javax.swing.JTextField textFieldAlterarTipoConta;
    // End of variables declaration//GEN-END:variables
}
