/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import javax.swing.JLabel;

/**
 *
 * @author PabloCarrijo
 */
public class ConsultaFunPane extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaFunPane
     */
    public ConsultaFunPane() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelNameInput = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelCPFInput = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelDataNascimentoInput = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelEstadoCivilInput = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelCargoEmpresarialInput = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelCEPInput = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelCidadeInput = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelBairroInput = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelRuaInput = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelNumeroEnderecoInput = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        labelComplementoEnderecoInput = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelTelefoneInput = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        labelEmailInput = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        labelSalarioInput = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        labelNomeBancoInput = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        labelAgenciaInput = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        labelNumeroContaInput = new javax.swing.JLabel();

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome completo :");

        labelNameInput.setForeground(new java.awt.Color(0, 0, 0));
        labelNameInput.setText(" -");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CPF :");

        labelCPFInput.setForeground(new java.awt.Color(0, 0, 0));
        labelCPFInput.setText(" -");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Data nascimento :");

        labelDataNascimentoInput.setForeground(new java.awt.Color(0, 0, 0));
        labelDataNascimentoInput.setText(" -");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Estado civil :");

        labelEstadoCivilInput.setForeground(new java.awt.Color(0, 0, 0));
        labelEstadoCivilInput.setText(" -");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cargo empresarial :");

        labelCargoEmpresarialInput.setForeground(new java.awt.Color(0, 0, 0));
        labelCargoEmpresarialInput.setText(" -");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("CEP :");

        labelCEPInput.setForeground(new java.awt.Color(0, 0, 0));
        labelCEPInput.setText(" -");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Cidade :");

        labelCidadeInput.setForeground(new java.awt.Color(0, 0, 0));
        labelCidadeInput.setText(" -");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Bairro :");

        labelBairroInput.setForeground(new java.awt.Color(0, 0, 0));
        labelBairroInput.setText(" -");

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Rua :");

        labelRuaInput.setForeground(new java.awt.Color(0, 0, 0));
        labelRuaInput.setText(" -");

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Número : ");

        labelNumeroEnderecoInput.setForeground(new java.awt.Color(0, 0, 0));
        labelNumeroEnderecoInput.setText(" -");

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Complemento : ");

        labelComplementoEnderecoInput.setForeground(new java.awt.Color(0, 0, 0));
        labelComplementoEnderecoInput.setText(" -");

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Telefone  : ");

        labelTelefoneInput.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefoneInput.setText(" -");

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Email :");

        labelEmailInput.setForeground(new java.awt.Color(0, 0, 0));
        labelEmailInput.setText(" -");

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Salário :");

        labelSalarioInput.setForeground(new java.awt.Color(0, 0, 0));
        labelSalarioInput.setText(" -");

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Nome do banco :");

        labelNomeBancoInput.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeBancoInput.setText(" -");

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Agência :");

        labelAgenciaInput.setForeground(new java.awt.Color(0, 0, 0));
        labelAgenciaInput.setText(" -");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/planing.png"))); // NOI18N

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Numero da conta: ");

        labelNumeroContaInput.setForeground(new java.awt.Color(0, 0, 0));
        labelNumeroContaInput.setText(" -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNameInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCPFInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(12, 12, 12)
                                .addComponent(labelDataNascimentoInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(labelEstadoCivilInput)))
                        .addGap(245, 245, 245))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCargoEmpresarialInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(12, 12, 12)
                                .addComponent(labelSalarioInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(12, 12, 12)
                                .addComponent(labelNomeBancoInput)))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(12, 12, 12)
                                .addComponent(labelComplementoEnderecoInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(12, 12, 12)
                                .addComponent(labelNumeroEnderecoInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(12, 12, 12)
                                .addComponent(labelBairroInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(12, 12, 12)
                                .addComponent(labelRuaInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(12, 12, 12)
                                .addComponent(labelTelefoneInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(12, 12, 12)
                                .addComponent(labelEmailInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(12, 12, 12)
                                .addComponent(labelCidadeInput))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addGap(12, 12, 12)
                                        .addComponent(labelNumeroContaInput))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(12, 12, 12)
                                        .addComponent(labelAgenciaInput)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addGap(147, 147, 147))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(labelCEPInput)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNameInput)
                    .addComponent(jLabel16)
                    .addComponent(labelCEPInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelCPFInput)
                            .addComponent(jLabel18)
                            .addComponent(labelCidadeInput))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(labelBairroInput))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(labelRuaInput))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelDataNascimentoInput)
                            .addComponent(jLabel24)
                            .addComponent(labelNumeroEnderecoInput))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labelEstadoCivilInput)
                            .addComponent(jLabel26)
                            .addComponent(labelComplementoEnderecoInput)))
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(labelTelefoneInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(labelEmailInput))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(labelAgenciaInput))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(labelNumeroContaInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(labelCargoEmpresarialInput))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(labelSalarioInput)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNomeBancoInput))))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelNumeroContaInput() {
        return labelNumeroContaInput;
    }

    public void setLabelNumeroContaInput(String value) {
        labelNumeroContaInput.setText(value);
    }
    
    public JLabel getLabelAgenciaInput() {
        return labelAgenciaInput;
    }

    public void setLabelAgenciaInput(String value) {
        labelAgenciaInput.setText(value);
    }

    public JLabel getLabelBairroInput() {
        return labelBairroInput;
    }

    public void setLabelBairroInput(String value) {
        labelBairroInput.setText(value);
    }

    public JLabel getLabelCEPInput() {
        return labelCEPInput;
    }

    public void setLabelCEPInput(String value) {
        labelCEPInput.setText(value);
    }

    public JLabel getLabelCPFInput() {
        return labelCPFInput;
    }

    public void setLabelCPFInput(String value) {
        labelCPFInput.setText(value);
    }

    public JLabel getLabelCargoEmpresarialInput() {
        return labelCargoEmpresarialInput;
    }

    public void setLabelCargoEmpresarialInput(String value) {
        labelCargoEmpresarialInput.setText(value);
    }

    public JLabel getLabelCidadeInput() {
        return labelCidadeInput;
    }

    public void setLabelCidadeInput(String value) {
        labelCidadeInput.setText(value);
    }

    public JLabel getLabelComplementoEnderecoInput() {
        return labelComplementoEnderecoInput;
    }

    public void setLabelComplementoEnderecoInput(String value) {
        labelComplementoEnderecoInput.setText(value);
    }

    public JLabel getLabelDataNascimentoInput() {
        return labelDataNascimentoInput;
    }

    public void setLabelDataNascimentoInput(String value) {
        labelDataNascimentoInput.setText(value);
    }

    public JLabel getLabelEmailInput() {
        return labelEmailInput;
    }

    public void setLabelEmailInput(String value) {
        labelEmailInput.setText(value);
    }

    public JLabel getLabelEstadoCivilInput() {
        return labelEstadoCivilInput;
    }

    public void setLabelEstadoCivilInput(String value) {
        labelEstadoCivilInput.setText(value);
    }

    public JLabel getLabelNameInput() {
        return labelNameInput;
    }

    public void setLabelNameInput(String value) {
        labelNameInput.setText(value);
    }

    public JLabel getLabelNomeBancoInput() {
        return labelNomeBancoInput;
    }

    public void setLabelNomeBancoInput(String value) {
        labelNomeBancoInput.setText(value);
    }

    public JLabel getLabelNumeroEnderecoInput() {
        return labelNumeroEnderecoInput;
    }

    public void setLabelNumeroEnderecoInput(String value) {
        labelNumeroEnderecoInput.setText(value);
    }

    public JLabel getLabelRuaInput() {
        return labelRuaInput;
    }

    public void setLabelRuaInput(String value) {
        labelRuaInput.setText(value);
    }

    public JLabel getLabelSalarioInput() {
        return labelSalarioInput;
    }

    public void setLabelSalarioInput(String value) {
        labelSalarioInput.setText(value);
    }

    public JLabel getLabelTelefoneInput() {
        return labelTelefoneInput;
    }

    public void setLabelTelefoneInput(String value) {
        labelTelefoneInput.setText(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelAgenciaInput;
    private javax.swing.JLabel labelBairroInput;
    private javax.swing.JLabel labelCEPInput;
    private javax.swing.JLabel labelCPFInput;
    private javax.swing.JLabel labelCargoEmpresarialInput;
    private javax.swing.JLabel labelCidadeInput;
    private javax.swing.JLabel labelComplementoEnderecoInput;
    private javax.swing.JLabel labelDataNascimentoInput;
    private javax.swing.JLabel labelEmailInput;
    private javax.swing.JLabel labelEstadoCivilInput;
    private javax.swing.JLabel labelNameInput;
    private javax.swing.JLabel labelNomeBancoInput;
    private javax.swing.JLabel labelNumeroContaInput;
    private javax.swing.JLabel labelNumeroEnderecoInput;
    private javax.swing.JLabel labelRuaInput;
    private javax.swing.JLabel labelSalarioInput;
    private javax.swing.JLabel labelTelefoneInput;
    // End of variables declaration//GEN-END:variables
}
