/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class ConsultaFun extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaFuncionario
     */
    
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    ConsultaFunPane consultaFunPane;
    
    public ConsultaFun() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldConsultaFun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        desktopPaneConsulta = new javax.swing.JDesktopPane();
        buttonConsulta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(80, 80, 80));

        jPanel1.setBackground(new java.awt.Color(80, 80, 80));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome para consulta");

        javax.swing.GroupLayout desktopPaneConsultaLayout = new javax.swing.GroupLayout(desktopPaneConsulta);
        desktopPaneConsulta.setLayout(desktopPaneConsultaLayout);
        desktopPaneConsultaLayout.setHorizontalGroup(
            desktopPaneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1327, Short.MAX_VALUE)
        );
        desktopPaneConsultaLayout.setVerticalGroup(
            desktopPaneConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        buttonConsulta.setText("Consultar");
        buttonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/arrow_left.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneConsulta)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(textFieldConsultaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addGap(57, 57, 57)
                .addComponent(buttonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1)
                                .addGap(13, 13, 13)
                                .addComponent(textFieldConsultaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(buttonConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPaneConsulta))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultaActionPerformed
        
        consultaFunPane = new ConsultaFunPane();
        desktopPaneConsulta.add(consultaFunPane);
        consultaFunPane.setSize(desktopPaneConsulta.getSize());
        consultaFunPane.setLocation(0, 0);
        consultaFunPane.show();
        
        try{
         
            conn = myConnection.getConexao();
            if(conn == null || conn.isClosed()){
                System.out.println("Impossivel estabelecer conexao...");
            }
            else System.out.println("Conexao estabelecida com sucesso...");
            
            String nameConsulta = textFieldConsultaFun.getText();
            
            String sql = "SELECT * FROM funcionarios WHERE nome = ?";
            
            ps = conn.prepareStatement(sql);
            
            ps.setString(1, nameConsulta);
            
            rs = ps.executeQuery();
            
            while(rs.next()){
                consultaFunPane.setLabelNameInput(rs.getString("nome"));
                consultaFunPane.setLabelCPFInput(rs.getString("cpf"));
                consultaFunPane.setLabelRGInput(rs.getString("rg"));
                consultaFunPane.setLabelNacionalidadeInput(rs.getString("nacionalidade"));
                consultaFunPane.setLabelDataNascimentoInput(rs.getString("data_nascimento"));
                consultaFunPane.setLabelEstadoCivilInput(rs.getString("estado_civil"));
                consultaFunPane.setLabelCargoEmpresarialInput(rs.getString("cargo"));
                consultaFunPane.setLabelCEPInput(rs.getString("cep"));
                consultaFunPane.setLabelCidadeInput(rs.getString("cidade"));
                consultaFunPane.setLabelBairroInput(rs.getString("bairro"));
                consultaFunPane.setLabelRuaInput(rs.getString("rua"));
                consultaFunPane.setLabelNumeroEnderecoInput(rs.getString("numero"));
                consultaFunPane.setLabelComplementoEnderecoInput(rs.getString("complemento"));
                consultaFunPane.setLabelTelefoneInput(rs.getString("telefone"));
                consultaFunPane.setLabelEmailInput(rs.getString("email"));
                consultaFunPane.setLabelNomeBancoInput(rs.getString("nome_banco"));
                consultaFunPane.setLabelSalarioInput(rs.getString("salario"));
                consultaFunPane.setLabelAgenciaInput(rs.getString("agencia"));
                consultaFunPane.setLabelTipoContaInput(rs.getString("tipo_conta"));
                consultaFunPane.setLabelNomeTitularInput(rs.getString("nome_titular"));
                consultaFunPane.setLabelCPFTitularInput(rs.getString("cpf_titular"));
            }
            
            textFieldConsultaFun.setText("");
            
        }
        catch(SQLException e){
            System.out.println("Erro com banco de dados" + e.getMessage());
        }
        finally{
            myConnection.closeConnection(conn, ps);
        }
        
    }//GEN-LAST:event_buttonConsultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConsulta;
    private javax.swing.JDesktopPane desktopPaneConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldConsultaFun;
    // End of variables declaration//GEN-END:variables
}
