/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class RemoverFun extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverFun
     */
    
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    RemoveFunPane removeFunPane;
    
    public RemoverFun() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        textFieldUsuarioDemitir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desktopPaneRemove = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(80, 80, 80));

        jPanel1.setBackground(new java.awt.Color(80, 80, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/arrow_left.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textFieldUsuarioDemitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsuarioDemitirActionPerformed(evt);
            }
        });

        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do usuário a demitir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textFieldUsuarioDemitir, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldUsuarioDemitir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopPaneRemoveLayout = new javax.swing.GroupLayout(desktopPaneRemove);
        desktopPaneRemove.setLayout(desktopPaneRemoveLayout);
        desktopPaneRemoveLayout.setHorizontalGroup(
            desktopPaneRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneRemoveLayout.setVerticalGroup(
            desktopPaneRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopPaneRemove)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktopPaneRemove))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldUsuarioDemitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsuarioDemitirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsuarioDemitirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        removeFunPane = new RemoveFunPane();
        desktopPaneRemove.add(removeFunPane);
        removeFunPane.setSize(desktopPaneRemove.getSize());
        removeFunPane.setLocation(0, 0);
        removeFunPane.show();
        
        try{
         
            conn = myConnection.getConexao();
            if(conn == null || conn.isClosed()){
                System.out.println("Impossivel estabelecer conexao...");
            }
            else System.out.println("Conexao estabelecida com sucesso...");
            
            String nameConsulta = textFieldUsuarioDemitir.getText();
            
            String sql = "SELECT * FROM funcionarios WHERE nome = ?";
            
            ps = conn.prepareStatement(sql);
            
            ps.setString(1, nameConsulta);
            
            rs = ps.executeQuery();
            
            while(rs.next()){
                removeFunPane.setLabelNameInput(rs.getString("nome"));
                removeFunPane.setLabelCPFInput(rs.getString("cpf"));
                removeFunPane.setLabelRGInput(rs.getString("rg"));
                removeFunPane.setLabelNacionalidadeInput(rs.getString("nacionalidade"));
                removeFunPane.setLabelDataNascimentoInput(rs.getString("data_nascimento"));
                removeFunPane.setLabelEstadoCivilInput(rs.getString("estado_civil"));
                removeFunPane.setLabelCargoEmpresarialInput(rs.getString("cargo"));
                removeFunPane.setLabelCEPInput(rs.getString("cep"));
                removeFunPane.setLabelCidadeInput(rs.getString("cidade"));
                removeFunPane.setLabelBairroInput(rs.getString("bairro"));
                removeFunPane.setLabelRuaInput(rs.getString("rua"));
                removeFunPane.setLabelNumeroEnderecoInput(rs.getString("numero"));
                removeFunPane.setLabelComplementoEnderecoInput(rs.getString("complemento"));
                removeFunPane.setLabelTelefoneInput(rs.getString("telefone"));
                removeFunPane.setLabelEmailInput(rs.getString("email"));
                removeFunPane.setLabelNomeBancoInput(rs.getString("nome_banco"));
                removeFunPane.setLabelSalarioInput(rs.getString("salario"));
                removeFunPane.setLabelAgenciaInput(rs.getString("agencia"));
                removeFunPane.setLabelTipoContaInput(rs.getString("tipo_conta"));
                removeFunPane.setLabelNomeTitularInput(rs.getString("nome_titular"));
                removeFunPane.setLabelCPFTitularInput(rs.getString("cpf_titular"));
            }
            
            textFieldUsuarioDemitir.setText("");
            
        }
        catch(SQLException e){
            System.out.println("Erro com banco de dados" + e.getMessage());
        }
        finally{
            myConnection.closeConnection(conn, ps);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPaneRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldUsuarioDemitir;
    // End of variables declaration//GEN-END:variables
}
