/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames_paciente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class AlterarFunPaneDadosBancarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarFunPaneDadosBancarios
     */
    private Connection conn = null;
    private PreparedStatement ps = null;
    private String nameConsulta;

    public AlterarFunPaneDadosBancarios(String nameConsulta) {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.nameConsulta = nameConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldAlterarSalario = new javax.swing.JTextField();
        textFieldAlterarAgencia = new javax.swing.JTextField();
        textFieldAlterarNomeBanco = new javax.swing.JTextField();
        textFieldAlterarNumeroConta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textFieldAlterarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarSalarioActionPerformed(evt);
            }
        });

        textFieldAlterarNumeroConta.setEditable(false);
        textFieldAlterarNumeroConta.setBackground(new java.awt.Color(102, 102, 102));
        textFieldAlterarNumeroConta.setForeground(new java.awt.Color(255, 255, 255));
        textFieldAlterarNumeroConta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldAlterarNumeroConta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textFieldAlterarNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarNumeroContaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero da conta:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome banco :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agência :");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Salario  :");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldAlterarAgencia)
                    .addComponent(textFieldAlterarSalario)
                    .addComponent(textFieldAlterarNomeBanco)
                    .addComponent(textFieldAlterarNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textFieldAlterarNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldAlterarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAlterarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAlterarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarSalarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (conn == null || conn.isClosed()) {
                conn = myConnection.getConexao();
            } else if (conn != null && !conn.isClosed()) {
                conn = myConnection.getConexao();
            }

            // Atualiza dados bancários
            String sqlBanco = "UPDATE dados_bancarios SET nome_banco = ?, agencia = ?, salario = ? WHERE numero_conta = ?";
            ps = conn.prepareStatement(sqlBanco);
            ps.setString(1, textFieldAlterarNomeBanco.getText());
            ps.setString(2, textFieldAlterarAgencia.getText());
            ps.setDouble(3, Double.parseDouble(textFieldAlterarSalario.getText()));
            ps.setInt(4, Integer.parseInt(textFieldAlterarNumeroConta.getText()));
            ps.executeUpdate();

            int n = ps.executeUpdate();

            if (n > 0) {
                JOptionPane.showInternalMessageDialog(getDesktopPane(), "Funcionario cadastrado com sucesso");
                this.dispose();
            } else {
                JOptionPane.showInternalMessageDialog(getDesktopPane(),  "Erro ao atualizar usuário");
            }

        } catch (SQLException e) {
            JOptionPane.showInternalMessageDialog(getDesktopPane(), "Erro ao conectar banco de dados..." + e.getMessage());
        } finally {
            myConnection.closeConnection(conn, ps);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void textFieldAlterarNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarNumeroContaActionPerformed

    public JTextField getTextFieldAlterarAgencia() {
        return textFieldAlterarAgencia;
    }

    public void setTextFieldAlterarAgencia(String value) {
        textFieldAlterarAgencia.setText(value);
    }

    public JTextField getTextFieldAlterarNomeBanco() {
        return textFieldAlterarNomeBanco;
    }

    public void setTextFieldAlterarNomeBanco(String value) {
        textFieldAlterarNomeBanco.setText(value);
    }

    public JTextField getTextFieldAlterarSalario() {
        return textFieldAlterarSalario;
    }

    public void setTextFieldAlterarSalario(String value) {
        textFieldAlterarSalario.setText(value);
    }

    public JTextField getTextFieldAlterarNumeroConta() {
        return textFieldAlterarNumeroConta;
    }

    public void setTextFieldAlterarNumeroConta(String value) {
        textFieldAlterarNumeroConta.setText(value);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldAlterarAgencia;
    private javax.swing.JTextField textFieldAlterarNomeBanco;
    private javax.swing.JTextField textFieldAlterarNumeroConta;
    private javax.swing.JTextField textFieldAlterarSalario;
    // End of variables declaration//GEN-END:variables
}
