/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frames_paciente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.connector.myConnection;

/**
 *
 * @author PabloCarrijo
 */
public class AlterarFunContato extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarFunContato
     */
    private Connection conn = null;
    private PreparedStatement ps = null;
    private String nameConsulta;
    private ResultSet rs = null;

    public AlterarFunContato(String nameConsulta) {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.nameConsulta = nameConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldAlterarEmail = new javax.swing.JTextField();
        textFieldAlterarTelefone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Email :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Telefone :");

        textFieldAlterarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlterarEmailActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldAlterarEmail)
                    .addComponent(textFieldAlterarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldAlterarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textFieldAlterarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(161, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAlterarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlterarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlterarEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (conn == null || conn.isClosed()) {
                conn = myConnection.getConexao();
            } else if (conn != null || !conn.isClosed()) {
                myConnection.closeConnection(conn, ps);
                conn = myConnection.getConexao();
            }

            String sqlId = "SELECT id_paciente FROM paciente "
                    + "WHERE cpf = ?";

            ps = conn.prepareStatement(sqlId);
            ps.setString(1, nameConsulta);
            rs = ps.executeQuery();
            int idPaciente = -1;
            if (rs.next()) {
                idPaciente = rs.getInt("id_paciente");
            }

            String sql = "UPDATE contato SET email = ?, telefone = ?"
                    + " WHERE id_paciente = ?";

            ps = conn.prepareStatement(sql);
            ps.setString(1, textFieldAlterarEmail.getText());
            ps.setString(2, textFieldAlterarTelefone.getText());
            ps.setInt(3, idPaciente);

            int n = ps.executeUpdate();

            if (n > 0) {
                JOptionPane.showInternalMessageDialog(getDesktopPane(), "Email do paciente alterado com sucesso");
            } else {
                JOptionPane.showInternalMessageDialog(getDesktopPane(), "Erro ao alterar email do paciente");
            }

        } catch (SQLException e) {
            System.out.println("Erro ao conectar com o banco " + e.getMessage());
        } finally {
            myConnection.closeConnection(conn, ps);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextField getTextFieldAlterarEmail() {
        return textFieldAlterarEmail;
    }

    public void setTextFieldAlterarEmail(String value) {
        textFieldAlterarEmail.setText(value);
    }

    public JTextField getTextFieldAlterarTelefone() {
        return textFieldAlterarTelefone;
    }

    public void setTextFieldAlterarTelefone(String value) {
        textFieldAlterarTelefone.setText(value);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldAlterarEmail;
    private javax.swing.JTextField textFieldAlterarTelefone;
    // End of variables declaration//GEN-END:variables
}
