/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appgerenciadefuncionarios;

import frames.ConsultaFun;
import frames.AddFun;
import frames.AlterarFun;
import frames.RemoverFun;
import java.awt.Font;

/**
 *
 * @author PabloCarrijo
 */
public class FormPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        setResizable(false);
        setSize(1300, 700);
        setLocationRelativeTo(null);
        setJMenuBar(null);
        
        buttonRemoverFun.setFont(new Font("Arial", Font.BOLD, 15));
        buttonAlterarFun.setFont(new Font("Arial", Font.BOLD, 15));
        buttonConsultarFun.setFont(new Font("Arial", Font.BOLD, 15));
        buttonAddFun.setFont(new Font("Arial", Font.BOLD, 15));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        buttonRemoverFun = new javax.swing.JButton();
        buttonAddFun = new javax.swing.JButton();
        buttonAlterarFun = new javax.swing.JButton();
        buttonConsultarFun = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddNovoFuncionario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setPreferredSize(new java.awt.Dimension(1300, 541));

        buttonRemoverFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/funcionarios.png"))); // NOI18N
        buttonRemoverFun.setText("Remover funcionário");
        buttonRemoverFun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRemoverFun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonRemoverFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverFunActionPerformed(evt);
            }
        });

        buttonAddFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/add.png"))); // NOI18N
        buttonAddFun.setText("Adicionar funcionário");
        buttonAddFun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAddFun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAddFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddFunActionPerformed(evt);
            }
        });

        buttonAlterarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/basket_put.png"))); // NOI18N
        buttonAlterarFun.setText("Alterar funcionário");
        buttonAlterarFun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAlterarFun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAlterarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarFunActionPerformed(evt);
            }
        });

        buttonConsultarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/planing.png"))); // NOI18N
        buttonConsultarFun.setText("Consultar funcionário");
        buttonConsultarFun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonConsultarFun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonConsultarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarFunActionPerformed(evt);
            }
        });

        desktopPane.setLayer(buttonRemoverFun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonAddFun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonAlterarFun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonConsultarFun, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRemoverFun, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(buttonAddFun, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(buttonAlterarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(buttonConsultarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAlterarFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConsultarFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(buttonRemoverFun, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu1.setText("Funcionarios");

        AddNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/add.png"))); // NOI18N
        AddNovoFuncionario.setText("Adicionar Funcionario");
        AddNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNovoFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(AddNovoFuncionario);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/appGerenciaFuncionarios/imagens/basket_put.png"))); // NOI18N
        jMenuItem1.setText("Pesquisar Funcionario");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNovoFuncionarioActionPerformed
        

    }//GEN-LAST:event_AddNovoFuncionarioActionPerformed

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void buttonConsultarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultarFunActionPerformed
        ConsultaFun consultaFun = new ConsultaFun();
        desktopPane.add(consultaFun);
        consultaFun.setSize(desktopPane.getSize());
        consultaFun.setLocation(0, 0);
        consultaFun.show();
    }//GEN-LAST:event_buttonConsultarFunActionPerformed

    private void buttonAlterarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarFunActionPerformed
        AlterarFun alterarFun = new AlterarFun();
        desktopPane.add(alterarFun);
        alterarFun.setSize(desktopPane.getSize());
        alterarFun.setLocation(0, 0);
        alterarFun.show();
    }//GEN-LAST:event_buttonAlterarFunActionPerformed

    private void buttonAddFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddFunActionPerformed
        AddFun fun = new AddFun();
        desktopPane.add(fun);
        fun.setSize(desktopPane.getSize());
        fun.setLocation(0, 0);
        fun.show();
    }//GEN-LAST:event_buttonAddFunActionPerformed

    private void buttonRemoverFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverFunActionPerformed
        RemoverFun removerFun = new RemoverFun();
        desktopPane.add(removerFun);
        removerFun.setSize(desktopPane.getSize());
        removerFun.setLocation(0, 0);
        removerFun.show();
    }//GEN-LAST:event_buttonRemoverFunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddNovoFuncionario;
    private javax.swing.JButton buttonAddFun;
    private javax.swing.JButton buttonAlterarFun;
    private javax.swing.JButton buttonConsultarFun;
    private javax.swing.JButton buttonRemoverFun;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
